# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6370, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import TYPE_CHECKING

from azure.mgmt.core import ARMPipelineClient
from msrest import Deserializer, Serializer

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from typing import Any, Optional

    from azure.core.credentials import TokenCredential

from ._configuration import DataProtectionClientConfiguration
from .operations import BackupVaultsOperations
from .operations import OperationResultOperations
from .operations import DataProtectionClientOperationsMixin
from .operations import Operations
from .operations import BackupPoliciesOperations
from .operations import BackupInstancesOperations
from .operations import RecoveryPointsOperations
from .operations import RecoveryPointOperations
from .operations import JobsOperations
from .operations import FindRestorableTimeRangesOperations
from .operations import JobOperations
from .operations import ExportJobsOperations
from .operations import ExportJobsOperationResultOperations
from . import models


class DataProtectionClient(DataProtectionClientOperationsMixin):
    """Open API 2.0 Specs for Azure Data Protection service.

    :ivar backup_vaults: BackupVaultsOperations operations
    :vartype backup_vaults: data_protection_client.operations.BackupVaultsOperations
    :ivar operation_result: OperationResultOperations operations
    :vartype operation_result: data_protection_client.operations.OperationResultOperations
    :ivar operations: Operations operations
    :vartype operations: data_protection_client.operations.Operations
    :ivar backup_policies: BackupPoliciesOperations operations
    :vartype backup_policies: data_protection_client.operations.BackupPoliciesOperations
    :ivar backup_instances: BackupInstancesOperations operations
    :vartype backup_instances: data_protection_client.operations.BackupInstancesOperations
    :ivar recovery_points: RecoveryPointsOperations operations
    :vartype recovery_points: data_protection_client.operations.RecoveryPointsOperations
    :ivar recovery_point: RecoveryPointOperations operations
    :vartype recovery_point: data_protection_client.operations.RecoveryPointOperations
    :ivar jobs: JobsOperations operations
    :vartype jobs: data_protection_client.operations.JobsOperations
    :ivar find_restorable_time_ranges: FindRestorableTimeRangesOperations operations
    :vartype find_restorable_time_ranges: data_protection_client.operations.FindRestorableTimeRangesOperations
    :ivar job: JobOperations operations
    :vartype job: data_protection_client.operations.JobOperations
    :ivar export_jobs: ExportJobsOperations operations
    :vartype export_jobs: data_protection_client.operations.ExportJobsOperations
    :ivar export_jobs_operation_result: ExportJobsOperationResultOperations operations
    :vartype export_jobs_operation_result: data_protection_client.operations.ExportJobsOperationResultOperations
    :param credential: Credential needed for the client to connect to Azure.
    :type credential: ~azure.core.credentials.TokenCredential
    :param subscription_id: The subscription Id.
    :type subscription_id: str
    :param str base_url: Service URL
    :keyword int polling_interval: Default waiting time between two polls for LRO operations if no Retry-After header is present.
    """

    def __init__(
        self,
        credential,  # type: "TokenCredential"
        subscription_id,  # type: str
        base_url=None,  # type: Optional[str]
        **kwargs  # type: Any
    ):
        # type: (...) -> None
        if not base_url:
            base_url = 'https://management.azure.com'
        self._config = DataProtectionClientConfiguration(credential, subscription_id, **kwargs)
        self._client = ARMPipelineClient(base_url=base_url, config=self._config, **kwargs)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self._serialize = Serializer(client_models)
        self._serialize.client_side_validation = False
        self._deserialize = Deserializer(client_models)

        self.backup_vaults = BackupVaultsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.operation_result = OperationResultOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.operations = Operations(
            self._client, self._config, self._serialize, self._deserialize)
        self.backup_policies = BackupPoliciesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.backup_instances = BackupInstancesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.recovery_points = RecoveryPointsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.recovery_point = RecoveryPointOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.jobs = JobsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.find_restorable_time_ranges = FindRestorableTimeRangesOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.job = JobOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.export_jobs = ExportJobsOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.export_jobs_operation_result = ExportJobsOperationResultOperations(
            self._client, self._config, self._serialize, self._deserialize)

    def close(self):
        # type: () -> None
        self._client.close()

    def __enter__(self):
        # type: () -> DataProtectionClient
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details):
        # type: (Any) -> None
        self._client.__exit__(*exc_details)
